# Generated by Django 5.2.17 on 2026-08-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='From @BotFather, e.g. 123456789:ABCdef...', max_length=128),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Group or channel chat ID, e.g. -1001234567890', max_length=64),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Send a Telegram message when a new booking is submitted.'),
        ),
    ]
