# Generated by Django 5.2.17 on 2026-08-25 10:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_telegram_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='blockeddate',
            options={'ordering': ['start_date'], 'verbose_name': 'Blocked date', 'verbose_name_plural': 'Blocked dates'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='bookingroom',
            options={'verbose_name': 'Booking room', 'verbose_name_plural': 'Booking rooms'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact message', 'verbose_name_plural': 'Contact messages'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'Gallery image', 'verbose_name_plural': 'Gallery images'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'Hero slide', 'verbose_name_plural': 'Hero slides'},
        ),
        migrations.AlterModelOptions(
            name='nearbyplace',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'Nearby place', 'verbose_name_plural': 'Nearby places'},
        ),
        migrations.AlterModelOptions(
            name='policypage',
            options={'ordering': ['title'], 'verbose_name': 'Policy page', 'verbose_name_plural': 'Policy pages'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-starts_at', 'id'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor', 'number'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'Room image', 'verbose_name_plural': 'Room images'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['ordering', 'base_price'], 'verbose_name': 'Room type', 'verbose_name_plural': 'Room types'},
        ),
        migrations.AlterModelOptions(
            name='seasonalprice',
            options={'ordering': ['start_date'], 'verbose_name': 'Seasonal price', 'verbose_name_plural': 'Seasonal prices'},
        ),
        migrations.AlterModelOptions(
            name='stathighlight',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'Stat highlight', 'verbose_name_plural': 'Stat highlights'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, max_length=64, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='hotel.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estimated_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Estimated total'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(max_length=120, verbose_name='Guest name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Guests'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='Reference code'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rooms',
            field=models.ManyToManyField(related_name='bookings', through='hotel.BookingRoom', to='hotel.room', verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='Special requests'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='hotel.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='nightly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nightly rate'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='hotel.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_text',
            field=models.CharField(blank=True, max_length=64, verbose_name='CTA text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CTA text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_text_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CTA text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_text_uz',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CTA text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_url',
            field=models.CharField(blank=True, default='/book/', max_length=255, verbose_name='CTA URL'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='hero/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='distance',
            field=models.CharField(blank=True, max_length=64, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='distance_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='distance_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='distance_uz',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='icon',
            field=models.CharField(blank=True, max_length=64, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_label',
            field=models.CharField(blank=True, max_length=64, verbose_name='Discount label'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_label_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Discount label'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_label_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Discount label'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_label_uz',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Discount label'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='ends_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ends at'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='starts_at',
            field=models.DateField(blank=True, null=True, verbose_name='Starts at'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=16, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.roomtype', verbose_name='Room type'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='rooms/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.roomtype', verbose_name='Room type'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='size_sqm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Size (m²)'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='seasonalprice',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='seasonalprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='seasonalprice',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='hotel.roomtype', verbose_name='Room type'),
        ),
        migrations.AlterField(
            model_name='seasonalprice',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='check_in_time',
            field=models.CharField(default='14:00', max_length=16, verbose_name='Check-in time'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='check_out_time',
            field=models.CharField(default='12:00', max_length=16, verbose_name='Check-out time'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Google Analytics ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Map latitude'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Map longitude'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='OG image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Aida Hotel', max_length=120, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='Aida Hotel', max_length=120, null=True, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_ru',
            field=models.CharField(default='Aida Hotel', max_length=120, null=True, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_uz',
            field=models.CharField(default='Aida Hotel', max_length=120, null=True, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='From @BotFather, e.g. 123456789:ABCdef...', max_length=128, verbose_name='Telegram bot token'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Group or channel chat ID, e.g. -1001234567890', max_length=64, verbose_name='Telegram chat ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Send a Telegram message when a new booking is submitted.', verbose_name='Telegram notifications'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Yandex Metrika ID'),
        ),
        migrations.AlterField(
            model_name='stathighlight',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='stathighlight',
            name='label',
            field=models.CharField(max_length=120, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='stathighlight',
            name='label_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='stathighlight',
            name='label_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='stathighlight',
            name='label_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='stathighlight',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='stathighlight',
            name='value',
            field=models.CharField(max_length=64, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='guest_name',
            field=models.CharField(max_length=120, verbose_name='Guest name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Rating'),
        ),
    ]
