# Generated by Django 5.2.17 on 2026-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_amenity_options_alter_blockeddate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(choices=[('UZS', "UZS (so'm)"), ('USD', 'USD ($)')], default='UZS', help_text='Shown next to all room prices on the website and in admin.', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Per night. Currency is set in Site settings (UZS or USD).', max_digits=10, verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='seasonalprice',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Per night. Uses the currency from Site settings.', max_digits=10, verbose_name='Price'),
        ),
    ]
