# Generated by Django 5.2.17 on 2026-08-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_currency_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Large photos are auto-resized (max ~1920px) to speed up upload.', upload_to='gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Large photos are auto-resized (max ~1920px) to speed up upload.', upload_to='hero/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(help_text='Large photos are auto-resized (max ~1920px) to speed up upload.', upload_to='rooms/', verbose_name='Image'),
        ),
    ]
