# Generated by Django 5.2.17 on 2026-09-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_image_upload_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[('UZS', "UZS (so'm)"), ('USD', 'USD ($)'), ('EUR', 'EUR (€)')], default='UZS', help_text='Currency for this booking total (UZS, USD, or EUR).', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Per night. Currency is set in Site settings (UZS, USD, or EUR).', max_digits=10, verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(choices=[('UZS', "UZS (so'm)"), ('USD', 'USD ($)'), ('EUR', 'EUR (€)')], default='UZS', help_text='Default currency for room prices and new bookings: UZS, USD ($), or EUR (€).', max_length=3, verbose_name='Currency'),
        ),
    ]
