# Generated by Django 5.2.17 on 2026-09-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_currency_eur_and_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Group chat ID, usually starts with -100 (NOT the bot token/ID). Add the bot to the group, send a message, then open https://api.telegram.org/bot<TOKEN>/getUpdates and copy chat.id', max_length=64, verbose_name='Telegram chat ID'),
        ),
    ]
